#소스코드 빌드/배포 자동화에 사용될 스크립트입니다.
#runner에서 executor로 shell을 선택했기 때문에 script의 라인들은 각각 shell에서의 명령어가 된다.

#stages: 수행할 작업(job)을 실행할 시기를 정의. 즉, 파이프라인의 단계를 정의. 
#작성한 순서대로 실행. build->test->deploy
stages:
  - build
  - test


build-job:
  stage: build
  only:
    - master    #해당 작업은 master 브랜치에서만 실행
  script:
    - echo "build start"
    - dir

unit-test-job:
  stage: test
  only:
    - master
  script:
    - echo "unit test start"

