app:
  name: gimisangung
  description: This is the production environment
  version: 1.0.0

spring:
  url: https://i11a402.p.ssafy.io
  config:
    import:
      - classpath:yaml/api-key.yml
  application:
    name: gimisangung
  datasource:
    url: jdbc:mariadb://172.20.0.1:3306/gimisangung
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: ssafy
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
  data:
    mongodb:
      uri: mongodb://root:ssafy@172.20.0.1:27017/gimisangung
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

fastAPI:
  uri: http://172.20.0.4:5501/contract

server:
  port: 5500
  servlet:
    session:
      cookie:
        same-site: None
        secure: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE