package com.readwe.gimisangung.contract.model.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ContractStatus {
	FAIL("fail"),
	UPLOAD("upload"),
	ANALYZE("analyze"),
	// DONE("done"),
	ANALYZE_INIT("ANALYZE_INIT"),
	ANALYZE_OCR_START("ANALYZE_OCR_START"),
	ANALYZE_OCR_DONE("ANALYZE_OCR_DONE"),
	ANALYZE_TOKENIZE_START("ANALYZE_TOKENIZE_START"),
	ANALYZE_TOKENIZE_DONE("ANALYZE_TOKENIZE_DONE"),
	ANALYZE_CORRECTION_START("ANALYZE_CORRECTION_START"),
	ANALYZE_CORRECTION_END("ANALYZE_CORRECTION_END"),
	ANALYZE_CHECK_START("ANALYZE_CHECK_START"),
	ANALYZE_CHECK_END("ANALYZE_CHECK_END"),
	TAG_GEN_START("TAG_GEN_START"),
	TAG_GEN_END("TAG_GEN_END"),
	DONE("DONE");
	private final String status;
}
